before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./cmd/static-generator/main.go
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: cmd/docuowl/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: docuowl
      name: homebrew-tap
    commit_author:
      name: Victor Gama
      email: hey@vito.io
    folder: Formula
    license: "MIT"
    homepage: "https://github.com/docuowl/docuowl"
    description: "A documentation generator"
    conflicts:
      - docuowl
    test: |
        system "#{bin}/docuowl -v"
