before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./cmd/static-generator/main.go
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: cmd/docuowl/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
